<?php

namespace App\Observers;

use App\Models\Skp;

class SkpObserver
{

    /**
     * Handle the Skp "saved" event.
     *
     * @param  \App\Models\Skp  $skp
     * @return void
     */
    public function created(Skp $skp)
    {

        $kinerja = $skp->kinerjas()->create([
            'kategori' => 'utama',
            'deskripsi' => 'Terlaksananya tugas pokok manajerial, pengembangan kewirausahaan, dan supervisi kepada guru dan tenaga kependidikan',
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya kegiatan perencanaan dan pelaksanaan pembelajaran, evaluasi dan penilaian, analisis hasil pembelajaran dan pelaksanaan tindak lanjut hasil penilaian',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Membuat adminstrasi pembelajaran.\n 2. Melaksanakan pembelajaran \n 3. Melakukan evalusi \n 4. Menganalisis hasil evaluasi \n5. Melakukan tindak lanjut",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '50',
            'pekerjaan' => 'Semua Guru',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Administrasi pembelajaran (Buku 1,2,3,4)',
            'detail_output_kualitas' => 'Administrasi pembelajaran disusun dan diajarkan sesuai standar K-2013',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya tugas dan fungsi Wakil Kepala Sekolah/Madrasah pertahun',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Menyusun Program Kerja wakil Kepala Sekolah",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '50',
            'pekerjaan' => 'Wakil Kepala Sekolah',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Administrasi Wakil Kepala Sekolah',
            'detail_output_kualitas' => 'Administrasi Wakil Kepala Sekolah',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya tugas dan fungsi ketua program keahlian/program studi atau yang sejenisnya',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Menyusun Program Kerja Ketua program keahlian atau program studi",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '50',
            'pekerjaan' => 'Ketua Prog. Keahlian',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Administrasi Ketua Program Keahlian',
            'detail_output_kualitas' => 'Administrasi Ketua Program Keahlian',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya tugas dan fungsi kepala laboratorium',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Menyusun program kerja kepala laboratorium",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '50',
            'pekerjaan' => 'Kepala Bengkel',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Administrasi Kepala Bengkel',
            'detail_output_kualitas' => 'Administrasi Kepala Bengkel',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya tugas dan fungsi kepala laboratorium',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Menyusun program kerja kepala laboratorium",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '50',
            'pekerjaan' => 'Kepala Laboratorium',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Administrasi Kepala Laboratorium',
            'detail_output_kualitas' => 'Administrasi Kepala Laboratorium',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya tugas dan fungsi kepala unit produksi',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Menyusun program kerja kepala unit produksi",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '50',
            'pekerjaan' => 'Kepala Unit Produksi',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Administrasi Kepala Unit Produksi',
            'detail_output_kualitas' => 'Administrasi Kepala Unit Produksi',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya tugas dan fungsi kepala perpustakaan',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Menyusun program kerja kepala perpustakaan",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '50',
            'pekerjaan' => 'Ketua Prog. Keahlian, Kepala Laboratorium, Kepala Unit Produksi',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Administrasi Kepala Perpustakaan',
            'detail_output_kualitas' => 'Administrasi Kepala Perpustakaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya pembimbingan khusus pada satuan pendidikan yang menyelenggarakan pendidikan inklusi, pendidikan terpadu atau yang sejenisnya.',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Melakukan pembimbingan khusus pada satuan pendidikan yang menyelenggarakan pendidikan inklusi, pendidikan terpadu atau yang sejenisnya.",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Pembibingan',
            'detail_output_kualitas' => 'Administrasi Kepala Laboratoirum',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya tugas dan fungsi wali kelas',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Melaksanakanpembimbingan dan pembinaan terhadap peserta didik dikelasnya",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Wali Kelas',
            'detail_output_kualitas' => 'Administrasi Wali Kelas',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya penyusunan kurikulum pada satuan pendidikannya',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Menyusun kurikulum pada satuan pendidikannya",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Penyusunan Kurikulum',
            'detail_output_kualitas' => 'Kurikulum yang sesuai Standar',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya pengawasan penilaian dan evaluasi terhadap  proses dan hasil belajar.',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Melaksanakan pengawasan penilaian dan evaluasi terhadap  proses dan hasil belajar.",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Kegiatan Pegawasan',
            'detail_output_kualitas' => 'Kegiatan Pengawasan berjalan lancar, aman, dan tertib',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terbimbingnya guru pemula dalam program induksi',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Membimbing guru pemula dalam program induksi",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Guru pemula yang kompeten ',
            'detail_output_kualitas' => 'Kompetensi guru pemula dianggap terampil',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terbimbingnya siswa dalam kegiatan ekstrakurikuler',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Membimbing siswa dalam kegiatan ekstrakurikuler ",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Kegiatan bimbingan',
            'detail_output_kualitas' => 'Siswa terampil dalam kegiatan ekstrakurikuler',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya pembimbingan pada penyusunan publikasi ilmiah dan karya inovatif',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Melaksanakan pembimbingan pada penyusunan publikasi ilmiah dan karya inovatif",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Guru/Siswa yang dibimbing pada penyusunan PI/KI',
            'detail_output_kualitas' => 'Guru/Siswa yang dibimbing mampu menyusun PI/KI dengan baik',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Terlaksananya pembimbingan pada kelas yang menjadi tanggungjawabnya (khusus Guru Kelas)',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "Melaksanakan pembimbingan pada kelas yang menjadi tanggungjawabnya (khusus Guru Kelas)",
            'output_kegiatan' => "Laporan PKG",
            'tipe_angka_kredit' => 'persen',
            'angka_kredit' => '5',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan PKG',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Laporan Guru Kelas',
            'detail_output_kualitas' => 'Administrasi Guru Kelas',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);

        $kinerja = $skp->kinerjas()->create([
            'kategori' => 'tambahan',
            'deskripsi' => 'Terlaksananya Kegeiatan Perencanaan dan Pelaksanaan Pengembangan Keprofesian Berkelanjutan (PKB)',
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah mengikuti diklat fungsional lamanya lebih dari 960 jam',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti pelatihan \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil diklat \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '15',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan diklat fungsional yang diikuti linier',
            'indikator_kualitas' => 'Kegiatan diklat fungsional yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Diklat fungsional yang linear',
            'detail_output_kualitas' => 'Diklat fungsional berkategori BAIK',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah mengikuti diklat fungsional lamanya antara 641 s.d  960 jam',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti pelatihan \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil diklat \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '9',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan diklat fungsional yang diikuti linier',
            'indikator_kualitas' => 'Kegiatan diklat fungsional yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Diklat fungsional yang linear',
            'detail_output_kualitas' => 'Diklat fungsional berkategori BAIK',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah mengikuti diklat fungsional lamanya antara 481 s.d  640 jam',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti pelatihan \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil diklat \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '6',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan diklat fungsional yang diikuti linier',
            'indikator_kualitas' => 'Kegiatan diklat fungsional yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Diklat fungsional yang linear',
            'detail_output_kualitas' => 'Diklat fungsional berkategori BAIK',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah mengikuti diklat fungsional lamanya antara 181 s.d  480 jam',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti pelatihan \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil diklat \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '3',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan diklat fungsional yang diikuti linier',
            'indikator_kualitas' => 'Kegiatan diklat fungsional yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Diklat fungsional yang linear',
            'detail_output_kualitas' => 'Diklat fungsional berkategori BAIK',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah mengikuti diklat fungsional lamanya antara 81 s.d  180 jam',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti pelatihan \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil diklat \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '3',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan diklat fungsional yang diikuti linier',
            'indikator_kualitas' => 'Kegiatan diklat fungsional yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Diklat fungsional yang linear',
            'detail_output_kualitas' => 'Diklat fungsional berkategori BAIK',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah mengikuti diklat fungsional lamanya antara 30 s.d  80 jam',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti pelatihan \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil diklat \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '3',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan diklat fungsional yang diikuti linier',
            'indikator_kualitas' => 'Kegiatan diklat fungsional yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Diklat fungsional yang linear',
            'detail_output_kualitas' => 'Diklat fungsional berkategori BAIK',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah mengikuti kegiatan lokakarya atau kegiatan bersama (seperti KKG/MGMP/MKKS/K3S) untuk penyusunan perangkat kurikulum dan atau pembelajaran ',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti lokakarya/kegiatan bersama \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil lokakarya/kegiatan bersama \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.15',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan Lokakarya/Kegiatan bersama relevan dengan tugas dan fungsi',
            'indikator_kualitas' => 'Kegiatan Lokakarya/Kegiatan bersama minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Lokakarya/Kegiatan Bersama',
            'detail_output_kualitas' => 'Lokakarya/Kegiatan Bersama berkategori BAIK',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Telah menjadi pembahas pada kegiatan ilmiah',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti kegiatan ilmiah \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil kegiatan ilmiah \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.20',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan Ilmiah yang diikuti relevan dengan tugas dan fungsi',
            'indikator_kualitas' => 'Kegiatan Ilmiah yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai pemateri/pembahas',
            'detail_output_kuantitas' => 'Kegiatan Ilmiah',
            'detail_output_kualitas' => 'Kegiatan Ilmiah berkategori BAIK',
            'detail_output_waktu' => 'Jam setiap kegiatan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Menjadi peserta pada kegiatan ilmiah',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti kegiatan ilmiah \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil kegiatan ilmiah \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.10',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan Ilmiah yang diikuti relevan dengan tugas dan fungsi',
            'indikator_kualitas' => 'Kegiatan Ilmiah yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Kegiatan Ilmiah',
            'detail_output_kualitas' => 'Kegiatan Ilmiah berkategori BAIK',
            'detail_output_waktu' => 'Jam setiap kegiatan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);


        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Kegiatan kolektif lainnya yang sesuai dengan tugas dan kewajiban guru',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti kegiatan kolektif \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil kegiatan ilmiah \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.10',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Kegiatan Kolektif Non Ilmiah yang diikuti relevan dengan tugas dan fungsi',
            'indikator_kualitas' => 'Kegiatan Kolektif Non Ilmiah yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai peserta',
            'detail_output_kuantitas' => 'Kegiatan Kolektif Non Ilmiah',
            'detail_output_kualitas' => 'Kegiatan Kolektif Non Ilmiah berkategori BAIK',
            'detail_output_waktu' => 'Jam setiap kegiatan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Menjadi pemrasaran/nara sumber pada seminar atau lokakarya ilmiah',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti kegiatan ilmiah \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil kegiatan ilmiah \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.20',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Seminar / Lokakarya Ilmiah yang diikuti relevan dengan tugas dan fungsi',
            'indikator_kualitas' => 'Seminar / Lokakarya Ilmiah yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai narasumber/pembahas',
            'detail_output_kuantitas' => 'Seminar / Lokakarya Ilmiah',
            'detail_output_kualitas' => 'Seminar / Lokakarya Ilmiah berkategori BAIK',
            'detail_output_waktu' => 'Jam setiap kegiatan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Menjadi pemrasaran/nara sumber pada koloqium atau diskusi ilmiah',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Mengurus surat tugas \n 2. Mengikuti kegiatan ilmiah \n 3. Membuat laporan",
            'output_kegiatan' => "1. Surat tugas \n 2. Laporan hasil kegiatan ilmiah \n 3. Sertifikat",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.20',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Koloqium / Diskusi Ilmiah yang diikuti relevan dengan tugas dan fungsi',
            'indikator_kualitas' => 'Koloqium / Diskusi Ilmiah yang diikuti minimal berkategori BAIK',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan sebagai narasumber/pembahas',
            'detail_output_kuantitas' => 'Koloqium / Diskusi Ilmiah',
            'detail_output_kualitas' => 'Koloqium / Diskusi Ilmiah berkategori BAIK',
            'detail_output_waktu' => 'Jam setiap kegiatan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);


        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Adanya karya tulis berupa laporan hasil penelitian pada bidang pendidikan di sekolahnya, diterbitkan / dipublikasikan dalam bentuk buku ber ISBN dan diedarkan secara nasional atau telah lulus dari penilaian BNSP.',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Melakukan penelitian \n 2. Membuat laporan \n 3. Mengajukan ke penerbit",
            'output_kegiatan' => "Majalah/jurnal tingkat nasional",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '4',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Buku ber-ISBN',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Buku ber-ISBN',
            'detail_output_kualitas' => 'Isi buku sesuai dengan Kondisi Pembelajaran/Pendidikan Formal di Sekolah',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Adanya karya tulis berupa laporan hasil penelitian pada bidang pendidikan di sekolahnya, diterbitkan / dipublikasikan dalam majalah/jurnal ilmiah tingkat nasional.',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Melakukan penelitian \n 2. Membuat laporan \n 3. Mengajukan ke penerbit",
            'output_kegiatan' => "Majalah/jurnal tingkat nasional",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '3',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Majalah/jurnal tingkat nasional',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Majalah/jurnal tingkat nasional',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan Kondisi Pembelajaran/Pendidikan Formal di Sekolah',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Adanya karya tulis berupa laporan hasil penelitian pada bidang pendidikan di sekolahnya, diterbitkan / dipublikasikan dalam majalah/jurnal ilmiah tingkat provinsi',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Melakukan penelitian \n 2. Membuat laporan \n 3. Mengajukan ke penerbit",
            'output_kegiatan' => "Majalah/jurnal tingkat provinsi",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Majalah/jurnal tingkat provinsi',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Majalah/jurnal tingkat provinsi',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Adanya karya tulis berupa laporan hasil penelitian pada bidang pendidikan di sekolahnya, diterbitkan / dipublikasikan dalam majalah/jurnal ilmiah tingkat kabupaten/kota.',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Melakukan penelitian \n 2. Membuat laporan \n 3. Mengajukan ke penerbit",
            'output_kegiatan' => "Majalah/jurnal tingkat kabupaten/kota.",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Majalah/jurnal tingkat kabupaten/kota.',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_kuantitas' => 'Majalah/jurnal tingkat kabupaten/kota.',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);



        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Adanya karya tulis berupa  laporan hasil penelitian pada bidang pendidikan di sekolahnya, diseminarkan di sekolahnya, disimpan di perpustakaan. (PTK)',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Melakukan penelitian \n 2. Membuat laporan \n 3. Menseminarkan hasil peneitian \n 4. Menyimpan Laporan di perpustakaan",
            'output_kegiatan' => "Laporan hasil PTK",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '4',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Laporan hasil PTK yang dibuat sesuai standar penyusunan KTI (Asli, Penting, Ilmiah, Konsisten)',
            'indikator_kualitas' => 'Tingkat Kesesuaian Laporan PTK dengan permasalahan di sekolah atau di Kelas',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan untuk melakukan proses penelitan dan menyusun Laporan PTK',
            'detail_output_kuantitas' => 'Laporan PTK yang APIK',
            'detail_output_kualitas' => 'Laporan PTK yang Reliable',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);

        $kinerja->detailKinerjas()->create([
            'deskripsi' => 'Adanya makalah  berupa  tinjauan  ilmiah dalam bidang pendidikan formal dan pembelajaran pada satuan pendidikannya, tidak diterbitkan,  disimpan di perpustakaan.',
            'skp_id' => $skp->id,
            'butir_kegiatan' => "1. Melakukan penelitian \n 2. Membuat laporan \n 3. Menyimpan Laporan di perpustakaan",
            'output_kegiatan' => "Makalah tinjauan ilmiah",
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'pekerjaan' => '',
            'indikator_kuantitas' => 'Makalah tinjauan ilmiah yang dibuat asli dan bukan hasil plagiat',
            'indikator_kualitas' => 'Tingkat kesesuaian Makalah tinjauan ilmiah dengan Kondisi Pembelajaran/ Pendidikan Formal di Sekolah',
            'indikator_waktu' => 'Rata-rata waktu yang dibutuhkan untuk melakukan proses penelitan dan menyusun makalah',
            'detail_output_kuantitas' => 'Makalah Tinjuan Ilmiah yang memenuhi standar ',
            'detail_output_kualitas' => 'Isi makalah sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);

        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Adanya Artikel Ilmiah Populer di bidang pendidikan formal dan pembelajaran pada satuan pendidikannya dimuat di media masa tingkat nasional',
            'indikator_kuantitas' => 'Artikel media massa tingkat nasional',
            'butir_kegiatan' => "1. Melakukan penelitian/kajian ilmiah \n 2. Membuat laporan \n 3. Mempublikasi di media massa nasional",
            'output_kegiatan' => "Artikel media massa tingkat nasional",
            'detail_output_kuantitas' => 'Artikel media massa tingkat nasional',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' =>    'Isi artikel sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1.5',
            'deskripsi' => 'Adanya Artikel Ilmiah Populer di bidang pendidikan formal dan pembelajaran pada satuan pendidikannya dimuat di media masa tingkat provinsi (koran daerah).',
            'indikator_kuantitas' => 'Artikel media massa tingkat provinsi/koran daerah',
            'butir_kegiatan' => "1. Melakukan penelitian/kajian ilmiah \n 2. Membuat laporan \n 3. Mempublikasi di media massa provinsi(koran daerah)",
            'output_kegiatan' => "Artikel media massa tingkat provinsi/koran daerah",
            'detail_output_kuantitas' => 'Artikel media massa tingkat provinsi/koran daerah',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' =>    'Isi artikel ilmiah sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Adanya  Artikel Ilmiah dalam bidang pendidikan formal dan pembelajaran pada satuan pendidikannya dan dimuat di jurnal tingkat nasional yang terakreditasi',
            'indikator_kuantitas' => 'Jurnal tingkat nasional',
            'butir_kegiatan' => "1. Melakukan penelitian/kajian ilmiah \n 2. Membuat laporan \n 3. Mempublikasi pada jurnal nasional",
            'output_kegiatan' => "Jurnal tingkat nasional",
            'detail_output_kuantitas' => 'Jurnal tingkat nasional',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' =>    'Isi artikel ilmiah sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1.5',
            'deskripsi' => 'Adanya  Artikel Ilmiah dalam bidang pendidikan formal dan pembelajaran pada satuan pendidikannya dan dimuat di jurnal tingkat nasional yang tidak terakreditasi/ tingkat provinsi.',
            'indikator_kuantitas' => 'Jurnal tingkat provinsi',
            'butir_kegiatan' => "1. Melakukan penelitian/kajian ilmiah \n 2. Membuat laporan \n 3. Mempublikasi pada jurnal provinsi",
            'output_kegiatan' => "Jurnal tingkat provinsi",
            'detail_output_kuantitas' => 'Jurnal tingkat provinsi',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' =>    'Isi artikel ilmiah sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Adanya Artikel Ilmiah dalam bidang pendidikan formal dan pembelajaran pada satuan pendidikannya dan dimuat di jurnal tingkat lokal (kabupaten/kota/ sekolah/ madrasah dstnya).',
            'indikator_kuantitas' => 'Jurnal tingkat kabupaten/sekolah',
            'butir_kegiatan' => "1. Melakukan penelitian/kajian ilmiah \n 2. Membuat laporan \n 3. Mempublikasi pada jurnal kabupaten/kota/sekolah",
            'output_kegiatan' => "Jurnal tingkat kabupaten/sekolah",
            'detail_output_kuantitas' => 'Jurnal tingkat kabupaten/sekolah',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' =>    'Isi artikel ilmiah sesuai dengan Kondisi Pendidikan Formal di Sekolah',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);

        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '6',
            'deskripsi' => 'Adanya buku pelajaran per judul yang lolos penilaian oleh BSNP',
            'indikator_kuantitas' => 'Buku pelajaran oleh BNSP',
            'butir_kegiatan' =>    "1. Melakukan kajian buku \n 2. Menyusun buku \n 3. Mengajukan ke penerbit \n 4. Mengajukan ISBN",
            'output_kegiatan' =>    'Buku pelajaran oleh BNSP',
            'detail_output_kuantitas' => 'Buku pelajaran oleh BNSP',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Buku Pelajaran sesuai dengan standar isi kurikulum ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '3',
            'deskripsi' => 'Adanya buku  pelajaran per judul yang dicetak oleh penerbit dan ber ISBN',
            'indikator_kuantitas' => 'Buku pelajaran ber-ISBN',
            'butir_kegiatan' =>    "1. Melakukan kajian buku \n 2. Menyusun buku \n 3. Mengajukan ke penerbit \n 4. Mengajukan ISBN",
            'output_kegiatan' =>    'Buku pelajaran ber-ISBN',
            'detail_output_kuantitas' => 'Buku pelajaran ber-ISBN',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Buku Pelajaran sesuai dengan standar isi kurikulum ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Adanya buku pelajaran perjudul dicetak oleh penerbit  tetapi belum ber-ISBN.',
            'indikator_kuantitas' => 'Buku pelajaran',
            'butir_kegiatan' =>    "1. Melakukan kajian buku \n 2. Menyusun buku \n 3. Mengajukan ke penerbit",
            'output_kegiatan' =>    'Buku pelajaran',
            'detail_output_kuantitas' => 'Buku pelajaran',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Buku Pelajaran sesuai dengan standar isi kurikulum ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1.5',
            'deskripsi' => 'Adanya modul/diktat yang digunakan di tingkat  Provinsi dengan pengesahan dari Dinas Pendidikan Provinsi.',
            'indikator_kuantitas' => 'Modul tingkat provinsi',
            'butir_kegiatan' =>    "1. Melakukan kajian modul \n 2. Menyusun modul \n 3. Mengajukan pengesahan ke dinas pendidikan provinsi",
            'output_kegiatan' =>    'Modul tingkat provinsi',
            'detail_output_kuantitas' => 'Modul tingkat provinsi',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Modul sesuai dengan standar isi kurikulum ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Adanya modul/diktat yang digunakan di tingkat  kota/kabupaten dengan pengesahan dari Dinas Pendidikan Kota/Kabupaten.',
            'indikator_kuantitas' => 'Modul tingkat kabupaten',
            'butir_kegiatan' =>    "1. Melakukan kajian modul \n 2. Menyusun modul \n 3. Mengajukan pengesahan ke dinas pendidikan kabupaten",
            'output_kegiatan' =>    'Modul tingkat kabupaten',
            'detail_output_kuantitas' => 'Modul tingkat kabupaten',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Modul sesuai dengan standar isi kurikulum ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.5',
            'deskripsi' => 'Adanya modul/diktat yang digunakan di tingkat sekolah/madrasah setempat',
            'indikator_kuantitas' => 'Modul tingkat sekolah',
            'butir_kegiatan' =>    "1. Melakukan kajian modul \n 2. Menyusun modul \n 3. Mengajukan pengesahan ke kepala sekolah",
            'output_kegiatan' =>    'Modul tingkat sekolah',
            'detail_output_kuantitas' => 'Modul tingkat sekolah',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Modul sesuai dengan standar isi kurikulum ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '3',
            'deskripsi' => 'Adanya buku dalam bidang pendidikan  dicetak oleh penerbit  dan ber-ISBN.',
            'indikator_kuantitas' => 'Buku di bidang pendidikan yang ber-ISBN',
            'butir_kegiatan' =>    "1. Melakukan kajian buku \n 2. Menyusun buku \n 3. Mengajukan ke penerbit \n 4. Mengajukan ISBN",
            'output_kegiatan' =>    'Buku di bidang pendidikan yang ber-ISBN',
            'detail_output_kuantitas' => 'Buku di bidang pendidikan yang ber-ISBN',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Buku sesuai dengan isu di bidang pendidikan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1.5',
            'deskripsi' => 'Adanya buku dalam bidang pendidikan dicetak oleh penerbit  tetapi  belum ber-ISBN.',
            'indikator_kuantitas' => 'Buku di bidang pendidikan',
            'butir_kegiatan' =>    "1. Melakukan kajian buku \n 2. Menyusun buku \n 3. Mengajukan ke penerbit",
            'output_kegiatan' =>    'Buku di bidang pendidikan',
            'detail_output_kuantitas' => 'Buku di bidang pendidikan',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi Buku sesuai dengan isu di bidang pendidikan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Adanya karya hasil terjemahan yang dinyatakan oleh kepala sekolah/madrasah tiap karya.',
            'indikator_kuantitas' => 'Karya hasil terjemahan',
            'butir_kegiatan' =>    "1. Menterjemahkan buku \n 2. Menyusun hasil terjemahan \n 3. Mengajukan pengesahan ke kepala sekolah",
            'output_kegiatan' =>    'Karya hasil terjemahan',
            'detail_output_kuantitas' => 'Karya hasil terjemahan',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi karya terjemahan sesuai dengan naskah aslinya',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1.5',
            'deskripsi' => 'Adanya buku pedoman guru',
            'indikator_kuantitas' => 'Buku pedoman guru',
            'butir_kegiatan' =>    "1. Menyusun buku pedoman guru \n 2. Mengajukan pengesahan ke kepala sekolah",
            'output_kegiatan' =>    'Buku pedoman guru',
            'detail_output_kuantitas' => 'Buku pedoman guru',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi buku pedoman sesuai dengan standar proses pembelajaran',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '4',
            'deskripsi' => 'Terlaksananya karya inovatif (KI) teknologi tepat guna kategori Kompleks  ',
            'indikator_kuantitas' => 'Karya teknologi tepat guna',
            'butir_kegiatan' => "Membuat laporan cara pembuatan dan penggunaan alat atau mesin di sertai foto karya teknologi",
            'output_kegiatan' => "Karya teknologi tepat guna",
            'detail_output_kuantitas' => 'Karya teknologi Kompleks',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan hasil karya yang diciptakan ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Terlaksananya karya inovatif (KI) teknologi tepat guna kategori Sederhana',
            'indikator_kuantitas' => 'Karya teknologi tepat guna',
            'butir_kegiatan' => "Membuat laporan cara pengembangan dan penggunaan alat atau mesin di sertai foto karya teknologi",
            'output_kegiatan' => "Karya teknologi tepat guna",
            'detail_output_kuantitas' => 'Karya teknologi Sederhana',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan hasil karya yang dikembangkan ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '4',
            'deskripsi' => 'Ditemukannya/diciptakannya karya seni kategori kompleks',
            'indikator_kuantitas' => 'Inovasi karya seni',
            'butir_kegiatan' => "Membuat laporan cara pembuatan disertai foto karya seni dan bukti formal kepemilikan dan keasliannya",
            'output_kegiatan' => "Inovasi karya seni",
            'detail_output_kuantitas' => 'Inovasi karya seni',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan hasil karya seni yang diciptakan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Ditemukannya/diciptakannya karya seni sederhana',
            'indikator_kuantitas' => 'Inovasi karya seni',
            'butir_kegiatan' => "Membuat laporan cara pengembangan disertai foto karya seni dan bukti formal kepemilikan dan keasliannya",
            'output_kegiatan' => "Inovasi karya seni",
            'detail_output_kuantitas' => 'Inovasi karya seni',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan hasil karya seni yang dikembangkan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Telah membuat/memodifikasi alat pelajaran kategori kompleks',
            'indikator_kuantitas' => 'Alat pelajaran',
            'butir_kegiatan' =>    "1. Membuat laporan cara pembuatan dan penggunaan alat pelajaran dilengkapi foto \n 2. Mengusulkan pengesahan dari kepala sekolah tentang penggunaan alat pelajaran tersebut",
            'output_kegiatan' =>    'Alat pelajaran kompleks',
            'detail_output_kuantitas' => 'Alat pelajaran kompleks',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan alat pelajaran yang dibuat',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Telah membuat/memodifikasi alat pelajaran kategori sederhana',
            'indikator_kuantitas' => 'Alat pelajaran',
            'butir_kegiatan' =>    "1. Membuat laporan cara pengembangan dan penggunaan alat pelajaran dilengkapi foto \n 2. Mengusulkan pengesahan dari kepala sekolah tentang penggunaan alat pelajaran tersebut",
            'output_kegiatan' =>    'Alat pelajaran sederhana',
            'detail_output_kuantitas' => 'Alat pelajaran sederhana',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan alat pelajaran yang dibuat',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Telah membuat/memodifikasi alat peraga kategori kompleks',
            'indikator_kuantitas' => 'Alat peraga',
            'butir_kegiatan' =>    "1. Membuat laporan cara pembuatan dan penggunaan alat peraga dilengkapi foto \n 2. Mengusulkan pengesahan dari kepala sekolah tentang penggunaan alat peraga tersebut",
            'output_kegiatan' =>    'Alat peraga kompleks',
            'detail_output_kuantitas' => 'Alat peraga kompleks',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan dengan dengan alat peraga yang dibuat',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Telah membuat/memodifikasi alat peraga kategori sederhana',
            'indikator_kuantitas' => 'Alat peraga',
            'butir_kegiatan' =>    "1. Membuat laporan cara pengembangan dan penggunaan alat peraga dilengkapi foto \n 2. Mengusulkan pengesahan dari kepala sekolah tentang penggunaan alat peraga tersebut",
            'output_kegiatan' =>    'Alat peraga sederhana',
            'detail_output_kuantitas' => 'Alat peraga sederhana',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan dengan dengan alat peraga yang dibuat',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '4',
            'deskripsi' => 'Telah membuat/memodifikasi alat praktikum kategori kompleks   ',
            'indikator_kuantitas' => 'Alat praktikum',
            'butir_kegiatan' =>    "1. Membuat laporan cara pembuatan dan penggunaan alat praktikum dilengkapi foto \n 2. Mengusulkan pengesahan dari kepala sekolah tentang penggunaan alat praktikum tersebut",
            'output_kegiatan' =>    'Alat praktikum kompleks',
            'detail_output_kuantitas' => 'Alat praktikum kompleks',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan alat praktikum yang dibuat',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Telah membuat/memodifikasi alat praktikum kategori sederhana',
            'indikator_kuantitas' => 'Alat praktikum',
            'butir_kegiatan' =>    "1. Membuat laporan cara pengembangan dan penggunaan alat praktikum dilengkapi foto \n 2. Mengusulkan pengesahan dari kepala sekolah tentang penggunaan alat praktikum tersebut",
            'output_kegiatan' =>    'Alat praktikum sederhana',
            'detail_output_kuantitas' => 'Alat praktikum sederhana',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Isi laporan sesuai dengan alat praktikum yang dibuat',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir)
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Telah mengikuti Kegiatan  Penyusunan Standar/ Pedoman/ Soal dan sejenisnya pada tingkat nasional. ',
            'indikator_kuantitas' => 'Standar/Pedoman/Soal pada tingkat nasional.',
            'butir_kegiatan' =>    "1. Membuat laporan kegiatan \n 2. Menyajikan hasil kegiatan berupa Standar/Pedoman/Soal tingkat nasional",
            'output_kegiatan' =>    'Soal Tingkat Nasional',
            'detail_output_kuantitas' => 'Soal Tingkat Nasional',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Soal yang disusun sesuai dengan Standar Isi (Kurikulum)',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Hari selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Telah mengikuti Kegiatan  Penyusunan Standar/ Pedoman/Soal dan sejenisnya pada tingkat provinsi.',
            'indikator_kuantitas' => 'Standar/ Pedoman/ Soal pada tingkat provinsi',
            'butir_kegiatan' =>    "1. Membuat laporan kegiatan \n 2. Menyajikan hasil kegiatan berupa Standar/Pedoman/Soal tingkat provinsi",
            'output_kegiatan' =>    'Soal Tingkat Provinsi',
            'detail_output_kuantitas' => 'Soal Tingkat Provinsi',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Soal yang disusun sesuai dengan Standar Isi (Kurikulum)',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Hari selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);

        $kinerja = $skp->kinerjas()->create([
            'kategori' => 'tambahan',
            'deskripsi' => 'Terlaksananya kegiatan yang mendukung tugas guru',
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.17',
            'deskripsi' => 'Terlaksananya pembimbingan siswa dalam praktik kerja nyata / praktik industri / ekstrakurikuler dan yang sejenisnya',
            'indikator_kuantitas' => 'Jumlah siswa yang dibimbing',
            'butir_kegiatan' => "1. Membimbing siswa dalam praktik kerja nyata/praktik industri/ekstrakurikuler \n 2. Membuat laporan hasil pembimbingan",
            'output_kegiatan' => "SK",
            'detail_output_kuantitas' => 'Siswa Terampil',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Siswa yang dibimbing dalam praktik kerja nyata dianggap terampil ',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.08',
            'deskripsi' => 'Telah menjadi pengawas ujian penilaian dan evaluasi terhadap proses dan hasil belajar tingkat sekolah',
            'indikator_kuantitas' => 'Jumlah ruangan yang diawasi',
            'butir_kegiatan' => "1. Melakukan pengawasan Ujian nasional di tingkat sekolah \n 2. Membuat laporan hasil pengawasan",
            'output_kegiatan' => "SK",
            'detail_output_kuantitas' => 'Ruangan Ujian',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Siswa mengikuti ujian dengan tertib, aman dan lancar',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.08',
            'deskripsi' => 'Telah menjadi pengawas ujian penilaian dan evaluasi terhadap proses dan hasil belajar tingkat nasional',
            'indikator_kuantitas' => 'Jumlah ruangan yang diawasi',
            'butir_kegiatan' => "1. Melakukan pengawasan Ujian nasional di tingkat nasional \n 2. Membuat laporan hasil pengawasan",
            'output_kegiatan' => "SK",
            'detail_output_kuantitas' => 'Ruangan Ujian',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Siswa mengikuti ujian dengan tertib, aman dan lancar',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.5',
            'deskripsi' => 'Telah menjadi anggota organisasi profesi, sebagai Pengurus aktif',
            'indikator_kuantitas' => 'Mempunyai SK/KTA',
            'butir_kegiatan' => "Menjadi pengurus aktif organisasi profesi",
            'output_kegiatan' => "SK Pengurus/KTA",
            'detail_output_kuantitas' => 'SK Pengurus/KTA',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Aktif sebagai pengurus organisasi',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.38',
            'deskripsi' => 'Telah menjadi anggota organisasi profesi, sebagai Anggota aktif',
            'indikator_kuantitas' => 'Mempunyai SK/KTA',
            'butir_kegiatan' => "Menjadi anggota aktif organisasi profesi",
            'output_kegiatan' => "SK Anggota/KTA",
            'detail_output_kuantitas' => 'SK Anggota/KTA',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Aktif sebagai anggota organisasi',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.5',
            'deskripsi' => 'Telah menjadi anggota kegiatan kepramukaan sebagai Pengurus aktif',
            'indikator_kuantitas' => 'Mempunyai SK/KTA',
            'butir_kegiatan' => "Menjadi pengurus aktif kegiatan kepramukaan",
            'output_kegiatan' => "SK Pengurus Kepramukaan",
            'detail_output_kuantitas' => 'SK Kegiatan Kepramukaan',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Aktif sebagai pengurus kegiatan kepramukaan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.38',
            'deskripsi' => 'Telah menjadi anggota kegiatan kepramukaan sebagai Anggota aktif',
            'indikator_kuantitas' => 'Mempunyai SK/KTA',
            'butir_kegiatan' => "Menjadi anggota aktif kegiatan kepramukaan",
            'output_kegiatan' => "SK anggota Kepramukaan",
            'detail_output_kuantitas' => 'SK Kegiatan Kepramukaan',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Aktif sebagai anggota kegiatan kepramukaan',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.02',
            'deskripsi' => 'Telah menjadi tim penilai angka kredit',
            'indikator_kuantitas' => 'Mempunyai SK',
            'butir_kegiatan' => "1. Melakukan penilaian angka kredit guru \n 2. Melaporkan hasil penilaian angka kredit guru",
            'output_kegiatan' => "DUPAK",
            'detail_output_kuantitas' => 'DUPAK',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Lampiran pendukung DUPAK sesuai dengan Bukti Fisiknya',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Pekan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '0.04',
            'deskripsi' => 'Telah menjadi tutor/pelatih/instruktur',
            'indikator_kuantitas' => 'Mempunyai SK',
            'butir_kegiatan' => "1. Melatih atau memberikan materi dalam suatu kegiatan \n 2. Menyusun laporan ",
            'output_kegiatan' => "SK Tutor/Pelatih/Instruktur",
            'detail_output_kuantitas' => 'SK Tutor/Pelatih/Instruktur',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Peserta yang dilatih berkategori terampil',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Jam setiap kegiatan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);

        $kinerja = $skp->kinerjas()->create([
            'kategori' => 'tambahan',
            'deskripsi' => 'Perolehan penghargaan/tanda jasa',
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '3',
            'deskripsi' => 'Telah memperoleh Penghargaan/tanda jasa Satya Lancana Karya Satya 30 (tiga puluh) tahun',
            'indikator_kuantitas' => 'Mempunyai sertifikat satyalancana',
            'butir_kegiatan' => "Melaksanakan pengabdian selama 30 tahun",
            'output_kegiatan' => "Sertifikat Satyalancana",
            'detail_output_kuantitas' => 'Sertifikat Satyalancana',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Sertifikat sesuai dengan masa pengabdian',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '2',
            'deskripsi' => 'Telah memperoleh Penghargaan/tanda jasa Satya Lancana Karya Satya 20 (dua puluh) tahun',
            'indikator_kuantitas' => 'Mempunyai sertifikat satyalancana',
            'butir_kegiatan' => "Melaksanakan pengabdian selama 20 tahun",
            'output_kegiatan' => "Sertifikat Satyalancana",
            'detail_output_kuantitas' => 'Sertifikat Satyalancana',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Sertifikat sesuai dengan masa pengabdian',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Telah memperoleh Penghargaan/tanda jasa Satya Lancana Karya Satya 10 (sepuluh) tahun',
            'indikator_kuantitas' => 'Mempunyai sertifikat satyalancana',
            'butir_kegiatan' => "Melaksanakan pengabdian selama 10 tahun",
            'output_kegiatan' => "Sertifikat Satyalancana",
            'detail_output_kuantitas' => 'Sertifikat Satyalancana',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Sertifikat sesuai dengan masa pengabdian',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
        $kinerja->detailKinerjas()->create([
            'skp_id' => $skp->id,
            'tipe_angka_kredit' => 'absolut',
            'angka_kredit' => '1',
            'deskripsi' => 'Telah memperoleh Penghargaan/tanda jasa',
            'indikator_kuantitas' => 'Mempunyai sertifikat penghargaan',
            'butir_kegiatan' => "Melakukan inovasi atau meraih prestasi",
            'output_kegiatan' => "Sertifikat/Piagam",
            'detail_output_kuantitas' => 'Sertifikat/Piagam',
            'indikator_kualitas' => 'Tercapai persentase sesuai harapan',
            'detail_output_kualitas' => 'Seritifikat/Piagam sesuai dengan Inovasi atau prestasi yang diraih',
            'indikator_waktu' => 'Ketepatan waktu pelaksanaan',
            'detail_output_waktu' => 'Bulan selama ' . format_periode($skp->periode_awal, $skp->periode_akhir),
        ]);
    }
}
